/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import static java.lang.Math.min;

/**
 *
 * @author Admin
 */
public class VueSolution extends JFrame {

    private final static int PADDING_FENETRE_RIGHT_ET_BOTTOM = 25;
    private final static int MARGIN_TOP_BOTTOM_WINDOW = 200;
    private final static int MARGIN_LEFT_RIGHT_WINDOW = 500;
    public final static Color BG_COLOR = Color.WHITE;
    public final static String CLOSE_BTN_IMAGE_STR = "ressources/index.png";

    private BufferedImage bufferedImageSolution;
    private BufferedImage closeBtnImage;
    private String imageStr;

    /**
     * Creates new form VueSolution
     */
    public VueSolution(String image) throws IOException {
        imageStr = image;
        bufferedImageSolution = ImageIO.read(new File(image));
        closeBtnImage = ImageIO.read(new File(CLOSE_BTN_IMAGE_STR));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(min(dim.width - MARGIN_LEFT_RIGHT_WINDOW, bufferedImageSolution.getWidth()+PADDING_FENETRE_RIGHT_ET_BOTTOM), min(dim.height-MARGIN_TOP_BOTTOM_WINDOW, bufferedImageSolution.getHeight() + PADDING_FENETRE_RIGHT_ET_BOTTOM));
        initComponents();
        //La fonction pack() moifie la hauteur de la fenetre. Je dois donc de nouveau modifier la taille
        this.setSize(min(dim.width - MARGIN_LEFT_RIGHT_WINDOW, bufferedImageSolution.getWidth()+PADDING_FENETRE_RIGHT_ET_BOTTOM), min(dim.height-MARGIN_TOP_BOTTOM_WINDOW, bufferedImageSolution.getHeight() + PADDING_FENETRE_RIGHT_ET_BOTTOM));
        initFenetre();
    }

    private void initFenetre(){
        setLocationRelativeTo(null);
        setBackground(BG_COLOR);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new JScrollPane();
        jPanel_image = new ImagePanel(imageStr);
        jButton1 = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        jButton1.setIcon(new ImageIcon(CLOSE_BTN_IMAGE_STR));
        jButton1.setBorder(BorderFactory.createEmptyBorder());
        jButton1.setContentAreaFilled(false);
        jButton1.setBorder(new EmptyBorder(10,0,0,50));

        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispose();
            }
        });

        GroupLayout jPanel_imageLayout = new GroupLayout(jPanel_image);
        jPanel_image.setLayout(jPanel_imageLayout);
        jPanel_imageLayout.setHorizontalGroup(
                jPanel_imageLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel_imageLayout.createSequentialGroup()
                                .addComponent(jButton1))
                        .addGap(0, bufferedImageSolution.getWidth(), Short.MAX_VALUE)
        );
        jPanel_imageLayout.setVerticalGroup(
                jPanel_imageLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_imageLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, bufferedImageSolution.getHeight()-closeBtnImage.getHeight(), Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel_image);
        add(jButton1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueSolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueSolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueSolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueSolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VueSolution("solution_ressources_draws/test.png").setVisible(true);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private ImagePanel jPanel_image;
    private JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
